spring.application.name=sheroute-backend
server.port=8081

external-apis.nominatim.base-url=https://nominatim.openstreetmap.org
external-apis.nominatim.user-agent=SheRouteMajorProject/1.0
external-apis.nominatim.email=sheroute@example.com
external-apis.osrm.base-url=https://router.project-osrm.org
external-apis.connect-timeout=5s
external-apis.read-timeout=10s
